name: mi_kalipepe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  carousel_slider: ^4.1.1
  sidebarx: ^0.4.0
  http: ^0.13.4
  flutter: 
    sdk: flutter
    

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/image/
    - assets/icon/
  uses-material-design: true

